/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as CampaignRequestsRouteImport } from './routes/campaign-requests'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CmTestRouteImport } from './routes/cm-test'
import { Route as CoordinatorLoginRouteImport } from './routes/coordinator-login'
import { Route as DoneraRouteImport } from './routes/donera'
import { Route as EcosystemViewRouteImport } from './routes/ecosystem-view'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyBlueDotsRouteImport } from './routes/my-blue-dots'
import { Route as RequestCampaignRouteImport } from './routes/request-campaign'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UserLevelAnalysisRouteImport } from './routes/user-level-analysis'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CampaignsCampaignRouteImport } from './routes/campaigns_.$campaign'
import { Route as ReviewCallIdRouteImport } from './routes/review_.$callId'
import { Route as ApiPublicHooksSyncSnapshotsRouteImport } from './routes/api/public/hooks/sync-snapshots'
import { Route as ApiPublicHooksZeffyWebhookRouteImport } from './routes/api.public/hooks.zeffy-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRequestsRoute = CampaignRequestsRouteImport.update({
  id: '/campaign-requests',
  path: '/campaign-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CmTestRoute = CmTestRouteImport.update({
  id: '/cm-test',
  path: '/cm-test',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorLoginRoute = CoordinatorLoginRouteImport.update({
  id: '/coordinator-login',
  path: '/coordinator-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneraRoute = DoneraRouteImport.update({
  id: '/donera',
  path: '/donera',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemViewRoute = EcosystemViewRouteImport.update({
  id: '/ecosystem-view',
  path: '/ecosystem-view',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBlueDotsRoute = MyBlueDotsRouteImport.update({
  id: '/my-blue-dots',
  path: '/my-blue-dots',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCampaignRoute = RequestCampaignRouteImport.update({
  id: '/request-campaign',
  path: '/request-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLevelAnalysisRoute = UserLevelAnalysisRouteImport.update({
  id: '/user-level-analysis',
  path: '/user-level-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignRoute = CampaignsCampaignRouteImport.update({
  id: '/campaigns_/$campaign',
  path: '/campaigns/$campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewCallIdRoute = ReviewCallIdRouteImport.update({
  id: '/review_/$callId',
  path: '/review/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncSnapshotsRoute =
  ApiPublicHooksSyncSnapshotsRouteImport.update({
    id: '/api/public/hooks/sync-snapshots',
    path: '/api/public/hooks/sync-snapshots',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksZeffyWebhookRoute =
  ApiPublicHooksZeffyWebhookRouteImport.update({
    id: '/api/public/hooks/zeffy-webhook',
    path: '/api/public/hooks/zeffy-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/campaign-requests': typeof CampaignRequestsRoute
  '/campaigns': typeof CampaignsRoute
  '/cm-test': typeof CmTestRoute
  '/coordinator-login': typeof CoordinatorLoginRoute
  '/donera': typeof DoneraRoute
  '/ecosystem-view': typeof EcosystemViewRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/my-blue-dots': typeof MyBlueDotsRoute
  '/request-campaign': typeof RequestCampaignRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/user-level-analysis': typeof UserLevelAnalysisRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$campaign': typeof CampaignsCampaignRoute
  '/review/$callId': typeof ReviewCallIdRoute
  '/api/public/hooks/sync-snapshots': typeof ApiPublicHooksSyncSnapshotsRoute
  '/api/public/hooks/zeffy-webhook': typeof ApiPublicHooksZeffyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/campaign-requests': typeof CampaignRequestsRoute
  '/campaigns': typeof CampaignsRoute
  '/cm-test': typeof CmTestRoute
  '/coordinator-login': typeof CoordinatorLoginRoute
  '/donera': typeof DoneraRoute
  '/ecosystem-view': typeof EcosystemViewRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/my-blue-dots': typeof MyBlueDotsRoute
  '/request-campaign': typeof RequestCampaignRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/user-level-analysis': typeof UserLevelAnalysisRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$campaign': typeof CampaignsCampaignRoute
  '/review/$callId': typeof ReviewCallIdRoute
  '/api/public/hooks/sync-snapshots': typeof ApiPublicHooksSyncSnapshotsRoute
  '/api/public/hooks/zeffy-webhook': typeof ApiPublicHooksZeffyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/campaign-requests': typeof CampaignRequestsRoute
  '/campaigns': typeof CampaignsRoute
  '/cm-test': typeof CmTestRoute
  '/coordinator-login': typeof CoordinatorLoginRoute
  '/donera': typeof DoneraRoute
  '/ecosystem-view': typeof EcosystemViewRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/my-blue-dots': typeof MyBlueDotsRoute
  '/request-campaign': typeof RequestCampaignRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/user-level-analysis': typeof UserLevelAnalysisRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns_/$campaign': typeof CampaignsCampaignRoute
  '/review_/$callId': typeof ReviewCallIdRoute
  '/api/public/hooks/sync-snapshots': typeof ApiPublicHooksSyncSnapshotsRoute
  '/api/public/hooks/zeffy-webhook': typeof ApiPublicHooksZeffyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/campaign-requests'
    | '/campaigns'
    | '/cm-test'
    | '/coordinator-login'
    | '/donera'
    | '/ecosystem-view'
    | '/launch'
    | '/login'
    | '/my-blue-dots'
    | '/request-campaign'
    | '/review'
    | '/settings'
    | '/user-level-analysis'
    | '/auth/callback'
    | '/campaigns/$campaign'
    | '/review/$callId'
    | '/api/public/hooks/sync-snapshots'
    | '/api/public/hooks/zeffy-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/campaign-requests'
    | '/campaigns'
    | '/cm-test'
    | '/coordinator-login'
    | '/donera'
    | '/ecosystem-view'
    | '/launch'
    | '/login'
    | '/my-blue-dots'
    | '/request-campaign'
    | '/review'
    | '/settings'
    | '/user-level-analysis'
    | '/auth/callback'
    | '/campaigns/$campaign'
    | '/review/$callId'
    | '/api/public/hooks/sync-snapshots'
    | '/api/public/hooks/zeffy-webhook'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/campaign-requests'
    | '/campaigns'
    | '/cm-test'
    | '/coordinator-login'
    | '/donera'
    | '/ecosystem-view'
    | '/launch'
    | '/login'
    | '/my-blue-dots'
    | '/request-campaign'
    | '/review'
    | '/settings'
    | '/user-level-analysis'
    | '/auth/callback'
    | '/campaigns_/$campaign'
    | '/review_/$callId'
    | '/api/public/hooks/sync-snapshots'
    | '/api/public/hooks/zeffy-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  CampaignRequestsRoute: typeof CampaignRequestsRoute
  CampaignsRoute: typeof CampaignsRoute
  CmTestRoute: typeof CmTestRoute
  CoordinatorLoginRoute: typeof CoordinatorLoginRoute
  DoneraRoute: typeof DoneraRoute
  EcosystemViewRoute: typeof EcosystemViewRoute
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
  MyBlueDotsRoute: typeof MyBlueDotsRoute
  RequestCampaignRoute: typeof RequestCampaignRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  UserLevelAnalysisRoute: typeof UserLevelAnalysisRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CampaignsCampaignRoute: typeof CampaignsCampaignRoute
  ReviewCallIdRoute: typeof ReviewCallIdRoute
  ApiPublicHooksSyncSnapshotsRoute: typeof ApiPublicHooksSyncSnapshotsRoute
  ApiPublicHooksZeffyWebhookRoute: typeof ApiPublicHooksZeffyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign-requests': {
      id: '/campaign-requests'
      path: '/campaign-requests'
      fullPath: '/campaign-requests'
      preLoaderRoute: typeof CampaignRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cm-test': {
      id: '/cm-test'
      path: '/cm-test'
      fullPath: '/cm-test'
      preLoaderRoute: typeof CmTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator-login': {
      id: '/coordinator-login'
      path: '/coordinator-login'
      fullPath: '/coordinator-login'
      preLoaderRoute: typeof CoordinatorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donera': {
      id: '/donera'
      path: '/donera'
      fullPath: '/donera'
      preLoaderRoute: typeof DoneraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem-view': {
      id: '/ecosystem-view'
      path: '/ecosystem-view'
      fullPath: '/ecosystem-view'
      preLoaderRoute: typeof EcosystemViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-blue-dots': {
      id: '/my-blue-dots'
      path: '/my-blue-dots'
      fullPath: '/my-blue-dots'
      preLoaderRoute: typeof MyBlueDotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-campaign': {
      id: '/request-campaign'
      path: '/request-campaign'
      fullPath: '/request-campaign'
      preLoaderRoute: typeof RequestCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-level-analysis': {
      id: '/user-level-analysis'
      path: '/user-level-analysis'
      fullPath: '/user-level-analysis'
      preLoaderRoute: typeof UserLevelAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns_/$campaign': {
      id: '/campaigns_/$campaign'
      path: '/campaigns/$campaign'
      fullPath: '/campaigns/$campaign'
      preLoaderRoute: typeof CampaignsCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review_/$callId': {
      id: '/review_/$callId'
      path: '/review/$callId'
      fullPath: '/review/$callId'
      preLoaderRoute: typeof ReviewCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-snapshots': {
      id: '/api/public/hooks/sync-snapshots'
      path: '/api/public/hooks/sync-snapshots'
      fullPath: '/api/public/hooks/sync-snapshots'
      preLoaderRoute: typeof ApiPublicHooksSyncSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/zeffy-webhook': {
      id: '/api/public/hooks/zeffy-webhook'
      path: '/api/public/hooks/zeffy-webhook'
      fullPath: '/api/public/hooks/zeffy-webhook'
      preLoaderRoute: typeof ApiPublicHooksZeffyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  CampaignRequestsRoute: CampaignRequestsRoute,
  CampaignsRoute: CampaignsRoute,
  CmTestRoute: CmTestRoute,
  CoordinatorLoginRoute: CoordinatorLoginRoute,
  DoneraRoute: DoneraRoute,
  EcosystemViewRoute: EcosystemViewRoute,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
  MyBlueDotsRoute: MyBlueDotsRoute,
  RequestCampaignRoute: RequestCampaignRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  UserLevelAnalysisRoute: UserLevelAnalysisRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CampaignsCampaignRoute: CampaignsCampaignRoute,
  ReviewCallIdRoute: ReviewCallIdRoute,
  ApiPublicHooksSyncSnapshotsRoute: ApiPublicHooksSyncSnapshotsRoute,
  ApiPublicHooksZeffyWebhookRoute: ApiPublicHooksZeffyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
